/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HuntsHuntIdRouteImport } from './routes/hunts/$huntId'
import { Route as HuntersHunterIdRouteImport } from './routes/hunters/$hunterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsHuntIdRoute = HuntsHuntIdRouteImport.update({
  id: '/hunts/$huntId',
  path: '/hunts/$huntId',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntersHunterIdRoute = HuntersHunterIdRouteImport.update({
  id: '/hunters/$hunterId',
  path: '/hunters/$hunterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hunters/$hunterId': typeof HuntersHunterIdRoute
  '/hunts/$huntId': typeof HuntsHuntIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hunters/$hunterId': typeof HuntersHunterIdRoute
  '/hunts/$huntId': typeof HuntsHuntIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hunters/$hunterId': typeof HuntersHunterIdRoute
  '/hunts/$huntId': typeof HuntsHuntIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hunters/$hunterId' | '/hunts/$huntId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hunters/$hunterId' | '/hunts/$huntId'
  id: '__root__' | '/' | '/hunters/$hunterId' | '/hunts/$huntId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HuntersHunterIdRoute: typeof HuntersHunterIdRoute
  HuntsHuntIdRoute: typeof HuntsHuntIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId': {
      id: '/hunts/$huntId'
      path: '/hunts/$huntId'
      fullPath: '/hunts/$huntId'
      preLoaderRoute: typeof HuntsHuntIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunters/$hunterId': {
      id: '/hunters/$hunterId'
      path: '/hunters/$hunterId'
      fullPath: '/hunters/$hunterId'
      preLoaderRoute: typeof HuntersHunterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HuntersHunterIdRoute: HuntersHunterIdRoute,
  HuntsHuntIdRoute: HuntsHuntIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
