/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthHuntsIndexRouteImport } from './routes/_auth/hunts/index'
import { Route as AuthHuntsHuntIdRouteImport } from './routes/_auth/hunts/$huntId'
import { Route as AuthHuntersHunterIdRouteImport } from './routes/_auth/hunters/$hunterId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHuntsIndexRoute = AuthHuntsIndexRouteImport.update({
  id: '/hunts/',
  path: '/hunts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHuntsHuntIdRoute = AuthHuntsHuntIdRouteImport.update({
  id: '/hunts/$huntId',
  path: '/hunts/$huntId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHuntersHunterIdRoute = AuthHuntersHunterIdRouteImport.update({
  id: '/hunters/$hunterId',
  path: '/hunters/$hunterId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthSettingsRoute
  '/hunters/$hunterId': typeof AuthHuntersHunterIdRoute
  '/hunts/$huntId': typeof AuthHuntsHuntIdRoute
  '/hunts': typeof AuthHuntsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthSettingsRoute
  '/hunters/$hunterId': typeof AuthHuntersHunterIdRoute
  '/hunts/$huntId': typeof AuthHuntsHuntIdRoute
  '/hunts': typeof AuthHuntsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/hunters/$hunterId': typeof AuthHuntersHunterIdRoute
  '/_auth/hunts/$huntId': typeof AuthHuntsHuntIdRoute
  '/_auth/hunts/': typeof AuthHuntsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/hunters/$hunterId'
    | '/hunts/$huntId'
    | '/hunts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/hunters/$hunterId' | '/hunts/$huntId' | '/hunts'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/settings'
    | '/_auth/hunters/$hunterId'
    | '/_auth/hunts/$huntId'
    | '/_auth/hunts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hunts/': {
      id: '/_auth/hunts/'
      path: '/hunts'
      fullPath: '/hunts'
      preLoaderRoute: typeof AuthHuntsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hunts/$huntId': {
      id: '/_auth/hunts/$huntId'
      path: '/hunts/$huntId'
      fullPath: '/hunts/$huntId'
      preLoaderRoute: typeof AuthHuntsHuntIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hunters/$hunterId': {
      id: '/_auth/hunters/$hunterId'
      path: '/hunters/$hunterId'
      fullPath: '/hunters/$hunterId'
      preLoaderRoute: typeof AuthHuntersHunterIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthHuntersHunterIdRoute: typeof AuthHuntersHunterIdRoute
  AuthHuntsHuntIdRoute: typeof AuthHuntsHuntIdRoute
  AuthHuntsIndexRoute: typeof AuthHuntsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSettingsRoute: AuthSettingsRoute,
  AuthHuntersHunterIdRoute: AuthHuntersHunterIdRoute,
  AuthHuntsHuntIdRoute: AuthHuntsHuntIdRoute,
  AuthHuntsIndexRoute: AuthHuntsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
